language: python
sudo: required
before_install:
  - sudo apt-get install -qq pkg-config python-dev
  # Pillow dependencies
  - sudo apt-get install -qq libtiff4-dev libjpeg8-dev zlib1g-dev libfreetype6-dev liblcms2-dev
  # PyAV dependencies
  - scripts/build-ffmpeg.sh
install:
  - pip install tox python-coveralls
script:
  - tox
after_success:
  - coveralls
env:
  - TOXENV=py27
