language: python
addons:
  apt:
    packages:
      - pkg-config
      - python-dev
      # PyAV depdendencies
      - libavformat-dev
      - libavcodec-dev
      - libavdevice-dev
      - libavutil-dev
      - libswscale-dev
      - libavresample-dev
      # Pillow dependencies
      - libtiff4-dev
      - libjpeg8-dev
      - zlib1g-dev
      - libfreetype6-dev
      - liblcms2-dev
install:
  - pip install tox python-coveralls
script:
  - tox
after_success:
  - coveralls
env:
  - TOXENV=py27
